### ISSUE TITLE
How to create CallBack with array object parameters?

### ISSUE THREAD

**Issue by menesty** [jnr/jnr-ffi#120]
I have function which expect callback handler like this 
void sp_set_debug_handler(void (*handler)(const char *format, ...));
now it is not allowed create callback with  array prams.
It is possible to get information from stout ?
library wrote debug information but I can't get it to analyze it

**Comment by goto1134** [comment]
try using `jnr.ffi.Pointer` as parameter instead of array.

**Comment by headius** [comment]
So the callback is literally varargs? That would be a bit trickier to map. It should be possible to do it through the appropriate C calls if you specify it as a pointer, though...

**Comment by unoexperto** [comment]
@goto1134 @headius Guys, could you please show example of passing callback function from Java to JNI ?

Here is function I want to pass
https://github.com/deephacks/lmdbjni/blob/23e6760120da7129f01ae39e5b5d274cc147eed0/lmdbjni/src/main/native-package/src/lmdb.h#L263

**Comment by headius** [comment]
I'm not sure if this is fixable and it's rather old now.

C compilers do very weird things with varargs, and I don't even know that it's possible to simulate it without actually compiling code. Sometimes values go in registers, so the `va_*` macros have to be very tricky to work properly.

If someone knows of a way to do this entirely via FFI, please let us know. For now I'm closing this.
