### ISSUE TITLE
Show example of passing callback function from Java to JNI

### ISSUE THREAD

**Issue by unoexperto** [jnr/jnr-ffi#124]
Guys, could you please show example of passing callback function from Java to JNI ?

Here is prototype of function I want to pass
https://github.com/deephacks/lmdbjni/blob/23e6760120da7129f01ae39e5b5d274cc147eed0/lmdbjni/src/main/native-package/src/lmdb.h#L263

I guess in Java it could be instance of `Comparator` class or something like that.

Thanks!

**Comment by unoexperto** [comment]
@headius @headius Guys, could you please suggest what to do ?

**Comment by pepijnve** [comment]
Starting from a C declaration like

```
typedef int  (MDB_cmp_func)(const MDB_val *a, const MDB_val *b);
```

you need to create an interface with a `@Delegate` annotated method that matches that signature. For instance,

```
public interface MDB_cmp_func {
  @Delegate
  public int func(Pointer a, Pointer b);
}
```

Function that accept this type of callback can then use this interface as parameter type so

```
int  mdb_set_compare(MDB_txn *txn, MDB_dbi dbi, MDB_cmp_func *cmp);
```

becomes

```
int  mdb_set_compare(Pointer txn, int dbi, MDB_cmp_func cmp);
```

There's one gotcha here. You need to make sure you keep a strong reference to your instances of the callback objects somewhere. JNR does not do this itself and you will get null pointer exception when the callback gets invoked if you don't keep a strong reference around somewhere.

**Comment by headius** [comment]
Looks like @pepijnve provided a good example, so there's nothing else to do here. This might be a good one to go into the [jnr-ffi-examples](https://github.com/jnr/jnr-ffi-examples) repository, if someone wants to create a PR for that.
