### ISSUE TITLE
Direct pointer size

### ISSUE THREAD

**Issue by goto1134** [jnr/jnr-ffi#132]
Is there a way to find out direct Pointer size? And if not, why?

**Comment by pepijnve** [comment]
Is `jnr.ffi.Runtime#addressSize` what you're looking for?

**Comment by goto1134** [comment]
I mean size of data written in direct memory. Analog of `sizeof` operation in C.

**Comment by pepijnve** [comment]
`sizeof` is a compile time operator in C. The type of the memory referenced by a Pointer object is unknown so you can't ask for the size of that. `Struct#size` is the closest thing I know of.

**Comment by goto1134** [comment]
Ok, thank you.
