### ISSUE TITLE
Is there a Mechanism to allocate a direct C-structure

### ISSUE THREAD

**Issue by cmosier** [jnr/jnr-ffi#133]
If I create a subclass of Struct, and just want to allocate it using libc's malloc, is there a way to get the size?  Is there a smarter way of doing this that I am missing?

Thanks.

**Comment by goto1134** [comment]
You can use Struct.size(new CustomStruct());

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by goto1134** [comment]
@cmosier did `Struct#size` method help you?

**Comment by cmosier** [comment]
Yes, this did help.  Instead of malloc, I used Memory.allocateDirect with the size, and that seems to work fine.  I am assuming that Memory.allocateDirect will clean itself up.  Thanks very much for the help!
