### ISSUE TITLE
Update ASM to 7.0

### ISSUE THREAD

**Issue by vjkoskela** [jnr/jnr-ffi#185]
The asm dependency in jnr-ffi is to version 5.0.3 ([pom.xml:50](https://github.com/jnr/jnr-ffi/blob/master/pom.xml#L50)) which was released in May 2014. The asm package was recently released as version 7.0:

https://search.maven.org/artifact/org.ow2.asm/asm/7.0/jar

It looks like there was an ask to shade the asm dependency in issue #96; however, if not possible or inline with the project's goals, would it be possible to update the asm dependency to the latest version and release a new version of jnr-ffi?

The problem we are having is that the older asm library is conflicting with other packages like cglib.

**Comment by ludoch** [comment]
Also needed to use Open JDK 11, the new Java version.

See https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/112

**Comment by vjkoskela** [comment]
The way I read that issue is that JDK-11 requires ASM 7. As far as I know ASM 7 is backwards compatible and does not require JDK-8. 

Section 5.1 of the ASM guide describes their backwards compatibility model:

https://asm.ow2.io/asm4-guide.pdf#page88

I’m curious if you have seen otherwise because we run ASM 7 on projects that compile/run on JDK/JRE 8.

**Comment by pepijnve** [comment]
I think this issue can be closed since JNR currently uses ASM 9.0

**Comment by headius** [comment]
@pepijnve Thanks for the triage!
