### ISSUE TITLE
Question: How to pass and read pointer to pointer to array

### ISSUE THREAD

**Issue by yana2301** [jnr/jnr-ffi#199]
Hello, 

I have a C function with following signature: 

static void func(long** labels, float** distances)

labels and distances are arrays, I want to be able to read them in Java code. 

Could you tell me please, how work with this function using jnr-ffi?

**Comment by headius** [comment]
The most direct way would be to just set them up as Pointer/MemoryAddress and use those APIs to read and write additional pointer values to/from that location.

The logic here is using Pointer to read and write simple int values, not pointers, but perhaps it's helpful: https://github.com/jnr/jnr-ffi-examples/blob/master/qsort/src/main/java/qsort/Qsort.java#L53

**Comment by headius** [comment]
I think it *might* be possible to set up these arguments as `Pointer[]` also... you'd still be responsible for dealing with the actual `long` and `float` pointers but it removes one level of complexity.

**Comment by yana2301** [comment]
@headius this is very helpful, thanks a lot for help!
