### ISSUE TITLE
Error building `jnr-ffi`on ppc64le platform

### ISSUE THREAD

**Issue by sarveshtamba** [jnr/jnr-ffi#200]
Trying to build `jnr-ffi` v2.1.7 and v2.1.12 (REPOSITORY="https://github.com/jnr/jnr-ffi.git") on ppc64le platform, however facing the following errors:-

```
Running jnr.ffi.NumberTest
Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.275 sec <<< FAILURE!
...
...
...
Results :

Failed tests:
  testBooleanFromInt(jnr.ffi.NumberTest)

Tests run: 289, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.965 s
[INFO] Finished at: 2020-04-17T11:06:40Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.4.2:test (default-test) on project jnr-ffi: There are test failures.
[ERROR]
[ERROR] Please refer to /root/jnr-ffi-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
sh-4.2#

```
Any inputs will be highly appreciated.

**Comment by sarveshtamba** [comment]
@headius any inputs on this one?

**Comment by headius** [comment]
@sarveshtamba Hello! Thanks for the report!

I will look into the failure today. However it may take some time since I don't have easy access to a ppc64le system.

**Comment by headius** [comment]
The function in question is defined as below and bound during tests:

```c
#define RET(T) T ret_##T(T arg1) { return arg1; }
```

So the bug here seems to be related to turning an int32 return type into a boolean.

**Comment by headius** [comment]
Ok for now I have requested access to a free educational OpenPower cloud, which hopefully will be sufficient to test and fix this.

@sarveshtamba Could you post the contents of the test output? The files should be under something named like "target/surefire-test-results" and there will be a .txt and a .xml file associated with this NumberTest class.

**Comment by headius** [comment]
Ok I have a power8 machine now!

Looks like this might be specific to the code-generated library logic. I turned that off with Java property `jnr.ffi.asm.enabled=false` and it no longer fails (though two other things do).

**Comment by headius** [comment]
Ah yes... it looks like the fallback logic for marshaling values does not consider anything but `1` to be true, while other paths allow any non-zero value to be treated as true (as in C).

**Comment by headius** [comment]
The fallback logic appears to fail a number of other tests (if I force it to always be used), so I'm opening a bug for that and we'll need to work on a PR for those cases.

Most of these cases probably aren't impacting you since the tests pass ok.

I have a fix for your failure during the build, and the test for that will be eventually enabling non-fast-numeric logic (the bug and PR I mentioned).

**Comment by headius** [comment]
@sarveshtamba This is fixed on master. Please confirm it works for you.

There's no additional test for it, since we would need to get #202 working. I would appreciate any help you can provide!

**Comment by sarveshtamba** [comment]
@headius I can now confirm that this issue is resolved and no longer appears on master.
Below is the output of the master build:-
```
[INFO] Building jar: /root/jnr-ffi-master/target/jnr-ffi-2.1.13-SNAPSHOT-javadoc.jar
[INFO]
[INFO] >>> maven-source-plugin:2.2.1:jar (attach-sources) > generate-sources @ jnr-ffi >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jnr-ffi ---
[INFO]
[INFO] <<< maven-source-plugin:2.2.1:jar (attach-sources) < generate-sources @ jnr-ffi <<<
[INFO]
[INFO]
[INFO] --- maven-source-plugin:2.2.1:jar (attach-sources) @ jnr-ffi ---
[INFO] Building jar: /root/jnr-ffi-master/target/jnr-ffi-2.1.13-SNAPSHOT-sources.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jnr-ffi ---
[INFO] Installing /root/jnr-ffi-master/target/jnr-ffi-2.1.13-SNAPSHOT.jar to /root/.m2/repository/com/github/jnr/jnr-ffi/2.1.13-SNAPSHOT/jnr-ffi-2.1.13-SNAPSHOT.jar
[INFO] Installing /root/jnr-ffi-master/pom.xml to /root/.m2/repository/com/github/jnr/jnr-ffi/2.1.13-SNAPSHOT/jnr-ffi-2.1.13-SNAPSHOT.pom
[INFO] Installing /root/jnr-ffi-master/target/jnr-ffi-2.1.13-SNAPSHOT-javadoc.jar to /root/.m2/repository/com/github/jnr/jnr-ffi/2.1.13-SNAPSHOT/jnr-ffi-2.1.13-SNAPSHOT-javadoc.jar
[INFO] Installing /root/jnr-ffi-master/target/jnr-ffi-2.1.13-SNAPSHOT-sources.jar to /root/.m2/repository/com/github/jnr/jnr-ffi/2.1.13-SNAPSHOT/jnr-ffi-2.1.13-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.922 s
[INFO] Finished at: 2020-04-22T04:55:25Z
[INFO] ------------------------------------------------------------------------
```
Thanks a lot for looking into this on priority. Appreciate all your help!

**Comment by headius** [comment]
@sarveshtamba Thank you! See also jnr/jnr-posix#144 which has also been mostly resolved (pending some additional work in jnr-constants).
