### ISSUE TITLE
Bi-Directional Struct-Array Parameter

### ISSUE THREAD

**Issue by Sammy1Am** [jnr/jnr-ffi#210]
I'm having some trouble retrieving data from C via an array-of-structs parameter.  I'm probably missing something obvious, but my array keeps coming back entirely null (other method calls and even IntByReference parameters in this function seem to be working fine.

C Code:
```c
typedef struct
{
    ...
} deviceStruct;

int getDevices(deviceStruct *devices, ...);
```

Java Code:
```java
public static class _DeviceT extends Struct {
        ...
        
        public _DeviceT(final jnr.ffi.Runtime runtime) {
            super(runtime);
        }
    }

public static interface MyAPI{
        int getDevices(@Direct @Out _DeviceT[] devices, ...);
    }

public static void main(String[] args) {
    MyAPI API = LibraryLoader.create(MyAPI.class).load("myapi");
    jnr.ffi.Runtime runtime = jnr.ffi.Runtime.getRuntime(API);

    // Creating a struct array this way (there are several options, not sure...)
    _DeviceT[] devices = Struct.arrayOf(runtime, _DeviceT.class, 16);
    int err = API.getDevices(devices, ...);
    // Expecting the devices variable to be populated now, but it's entirely empty
}
```

I've tried a few different ways to create the array, and different methods for defining the array parameter in the Java-interface (like Pointer, PointerByReference, etc.) but nothing seems to line up; either because the array is still null afterwards, or because I can't figure out how to pass an array of struct to whatever parameter I was trying out.  I have confirmed (via JNA and regular JNI) that the method usually seems to be working, but JNA and JNI each have issues with other parts of my project that JNR doesn't seem to have.

Can anyone point me in the right direction?

**Comment by Sammy1Am** [comment]
My issue ended up being in the `...`.  The struct needs to have all its fields statically (or at construction time) defined in Java (apparently).  Probably a memory-thing, but it's working now.

**Comment by headius** [comment]
👍
