### ISSUE TITLE
Is android Supported

### ISSUE THREAD

**Issue by paulo-raca** [jnr/jnr-ffi#215]
Hello,

I'm interested in using [jnr-unixsocket](https://github.com/jnr/jnr-unixsocket) in an Android Project, but unfortunately I got stuck on the jnr-ffi dependency, which doesn't find it's native libraries:

```java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/aarch64-Linux/libjffi-1.2.so, /jni/aarch64-Linux/libjffi-1.2.so]```

After looking at the sources for a bit, I couldn't find native libraries anywhere. The maven artifact (`com.github.jnr:jnr-ffi:2.2.1`) doesn't seen to have any native libraries either.

What am I missing? Is Android supported at all?
If not, how hard would it be to support it?

**Comment by headius** [comment]
The low level native library used by jnr-ffi is in the jffi project, which provides the native calling API in a Java jar and the native libraries for all platforms in a "native" jar. You can find both of those on Maven, as shown here:

https://search.maven.org/artifact/com.github.jnr/jffi/1.3.1/jar

The Linux/ARM native libraries that jffi includes do work on Android but may require some path adjustment to get picked up by your application. See issue https://github.com/jnr/jffi/issues/57for some discussion about the jffi libraries on Android.
