### ISSUE TITLE
Does UTF8String is zero-terminated after passing to C?

### ISSUE THREAD

**Issue by Alexander-94** [jnr/jnr-ffi#217]
Sorry for asking here, could you please help, there is not much JNR-FFI documentation)

I need to pass structure from Java to C and back
Structure contains mixed fields (char[], int, long...):
```
typedef struct test_fields{
    char field1[10];    
    int field2;
    char field3[10];
} TEST_FIELDS;
```
In Java I created class, extended from jnr.ffi.Struct and added fields:
```
public class TestStruct extends Struct {
    public static final int SIZE = 10;
    public static final int SIZE2 = 10;

    public final UTF8String field1 = new UTF8String(SIZE);
    public final Signed32 field2= new Signed32();
    public final UTF8String field3 = new UTF8String(SIZE2);

    protected TestStruct(Runtime runtime) {
        super(runtime);
    }
}
```
Created interface with signature of C calling function:
```
public static interface App{
        int main(TestStruct s);
}
```
Loading and calling my test lib like that:
```
App app1 = LibraryLoader.create(App.class).load("app.so");
Runtime runtime = Runtime.getRuntime(app1);
TestStruct t = new TestStruct(runtime);
t.field1.set("---------8");
t.field2.set(-1);
t.field3.set("---------9");
int ret = app1.main(t);
```

But when I print fields in C, I see that the last 10th symbol in both UTF8Strings is empty and is not passed from java
and I see only 9 dashes. Equal result gives TestStruct.toString(): (after calling app1.main)
```
TestStruct {
      SIZE = 10
      SIZE2 = 10
      field1 = ---------
      field2 = -1
      field3 = ---------
}
```

Why last symbol in UTF8String is lost?
Is my approach correct? 
How can I pass all UTF8String content by size to C? And correctly retrieve all fields back in Java
Or maybe there is another way to do it
Thank you

**Comment by headius** [comment]
Yes I believe the `char*` is null terminated and you would need to use a size of 11 for a 10-byte UTF-8 string. I agree the documentation is lacking here.

Your C struct, however, only has room for 10 chars. Are you expecting those strings to not be null terminated?

If you need to pass the string in the struct withou null termination, I believe you would need to set up the struct a bit differently, perhaps as a byte[] you populate with the Java String's UTF-8 bytes.

We do have a small repository of examples that could be improved to show passing strings to C code. Maybe you can come up with something and help explore the options? https://github.com/jnr/jnr-ffi-examples

**Comment by headius** [comment]
Hopefully you can come up with an example for https://github.com/jnr/jnr-ffi-examples but meanwhile I will close this issue.

**Comment by headius** [comment]
I have enabled Discussions so future questions can be posted there!
