### ISSUE TITLE
Support for apple m1

### ISSUE THREAD

**Issue by dhrsoni19** [jnr/jnr-ffi#226]
Currently, apple m1 is not supported. This library is being used my jnr-unixsocket which is used by fabric8io which helps with building docker containers using maven.

**Comment by headius** [comment]
We may be able to get this working now with the various patches for FFI. See https://github.com/jnr/jffi/issues/92

I am not sure of the status of libffi building on Apple Silicon but I believe the Ruby FFI gem is now working. We may just need to figure out what patches they are including.
