### ISSUE TITLE
Support for IBM i Platform

### ISSUE THREAD

**Issue by ThePrez** [jnr/jnr-ffi#230]
Currently, this package does not support the IBM i platform, which runs java in an AIX-derivative runtime called PASE. 

I plan to work on this and send PRs to jffi and jnr-jffi, but opening this issue to document my intents and ask questions along the way

**Comment by headius** [comment]
Sorry for no follow-up... it was a rough month. I will have a look at your PR and hope we can get this in the next release!

**Comment by headius** [comment]
I have merged the jffi support for iSeries but I guess we need a bit more here like the type mappings. As soon as you can make that happen, we'll have native support ready to go!

**Comment by headius** [comment]
So we are going to hold off on releasing the jffi bits since they won't fully work without some other bits in jnr-ffi and jnr-constants (at least). Really looking forward to your PRs so we can call this one done!

**Comment by ThePrez** [comment]
Fantastic! Thank you!
I will be sending a PR to jnr-ffi next week which should complete the support. I have all tests passing it as well as some creative smoke testing. Just needs a little more cleanup and verification

**Comment by headius** [comment]
Sounds good! I pushed 2.2.4 today but did not update jffi, since we probably don't want to ship partial iSeries support. We can push a new release any time.

**Comment by headius** [comment]
I believe this is resolved by #259 and jnr/jffi#103. Releasing now!
