### ISSUE TITLE
Update JUnit dependecy to JUnit5 ?

### ISSUE THREAD

**Issue by basshelal** [jnr/jnr-ffi#246]
Should we update to JUnit5 over the current 4.13.

As far as I can tell  we are JDK8+ which is the requirement for JUnit5.

JUnit5 brings a lot of improvements over JUnit4 and is the latest version.

This wouldn't be a bad thing to do to keep the codebase fresh and easier to maintain in the future.

It's also not too difficult to update too, some annotations need to be changed but not too much else as far as I know.

Should I pursue this?

**Comment by headius** [comment]
Sure, I see no reason not to make such an update.
