### ISSUE TITLE
could not load FFI provider jnr.ffi.provider.jffi.Provider

### ISSUE THREAD

**Issue by eneskuluk** [jnr/jnr-ffi#255]
Hi, I'm trying to implement a feature to a project via JNR but I'm having this issue: `could not load FFI provider jnr.ffi.provider.jffi.Provider`. 
I tested the feature standalone in seperate project and it was working on runtime,without compiling, running on the IDE was fine. I decided to merge this feature into to the main project but I'm having the former issue.

I have created dependencies on the main project, gave the classpath but we are running this project as a standalone package. And when we are running this as standalone, calling the class via spring results with former error.

Whole error is: 
```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.antmedia.srt.SRTHandler]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
```

**Comment by eneskuluk** [comment]
Found the cause, it wasn't able to locate native libraries(jffi.so files) somehow.

**Comment by 2246sam20** [comment]
Hey @eneskuluk  I am trying to run native Functions 
I am using Android studio and took reference from the JNR docs and 
public class HelloWorld {
    public interface LibC {
        int setenv(@In String name, @In String value, @In boolean overwrite);

        int unsetenv(@In String name);

        String getenv(@In String name);
        int clearenv();
        int puts(String s);
    }
    public static void main(String[] args) {
        Map<LibraryOption, Object> libraryOptions = new HashMap<>();
        libraryOptions.put(LibraryOption.LoadNow, true);
        libraryOptions.put(LibraryOption.IgnoreError, true);
        String libName = Platform.getNativePlatform().getStandardCLibraryName();

        LibC libc = LibraryLoader.loadLibrary(
                LibC.class,
                libraryOptions,
                libName
        );
        final String pwdKey = "PWD"; // key for working directory
        final String shellKey = "SHELL"; // key for system shell (bash, zsh etc)

//        String pwd = libc.getenv(pwdKey);
//        System.out.println(pwd); // prints current directory
//
//        libc.setenv(pwdKey, "/", true); // set PWD to /
//        System.out.println(libc.getenv(pwdKey)); // prints /
//
//        libc.unsetenv(pwdKey); // unset PWD
//        System.out.println(libc.getenv(pwdKey)); // prints null (it is null not the String "null")
//
//        System.out.println(libc.getenv(shellKey)); // prints system shell, /bin/bash on most Unixes
//        libc.clearenv(); // clear all environment variables
//        System.out.println(libc.getenv(shellKey)); // prints null (it is null not the String "null")
//        System.out.println(libc.getenv("_"));
        libc.puts("Hello World!");
        // even the special "_" environment variable is now null
    }

**Comment by 2246sam20** [comment]
Any help will be appreciated..
