### ISSUE TITLE
Multi-dimensional arrays as struct members

### ISSUE THREAD

**Issue by Tianscar** [jnr/jnr-ffi#325]
I'm writing bindings for libwebp using jnr-ffi, and while mapping the structs, I got a problem: 
```c
struct WebPAuxStats {
  ...
  int residual_bytes[3][4];  // approximate number of bytes spent for
                             // DC/AC/uv coefficients for each (0..3) segments.
  ...
};
```
The struct WebPAuxStats has a 2-d array among its members, but, as I can use the array() method for 1-d arrays, I cannot find similar methods for 2-d arrays. Does such methods exist? Or I have to map them as equivalent 1-d arrays?

**Comment by basshelal** [comment]
Unfortunately, you have to map them as equivalent 1-d arrays. We only have single dimension array methods.
