### ISSUE TITLE
Release new version of jnr-ffi

### ISSUE THREAD

**Issue by srisudarsan** [jnr/jnr-ffi#329]
WIth reference to https://github.com/jnr/jffi/issues/138 , a newer version of jnr-jffi was released 1.3.11 which makes it work with older linux systems with older glibc versions.

There is already change made to update the jnr-jffi version to 1.3.11 - https://github.com/jnr/jnr-ffi/commit/9ed4664ddf56d9603c074bc24ba031ce76ca0705 

This needs to be released

**Comment by headius** [comment]
Releasing today.
