### ISSUE TITLE
Why use JNR over JNA

### ISSUE THREAD

**Issue by walksanatora** [jnr/jnr-ffi#331]
They seem nearly identical

**Comment by enebo** [comment]
Here is one person's attempt at differentiating not only JNA but also JNI and project Panama.  There is also a link to someone's microbenchmarking with recent results to back up the performance difference: https://github.com/jnr/jnr-ffi/blob/master/docs/ComparisonToSimilarProjects.md.  Here is another talk about why JNR: https://www.oracle.com/technetwork/java/jvmls2013nutter-2013526.pdf
