### ISSUE TITLE
The annotations may be problematic.

### ISSUE THREAD

**Issue by yangsen-cn** [jnr/jnr-ffi#348]
In the Pointer.java class, line 414
```
@param idx the start index in the {@code dst} array to begin reading values.
```
Perhaps {@code dst} should be changed to {@code src}.
Because the method is ↓
```
abstract public void put(long offset, byte[] src, int idx, int len);
```

**Comment by headius** [comment]
Confirmed, this is likely referencing an old name for the `src` parameter.

I will fix this one manually. Perhaps you could help us out by submitting a PR to fix any other issues you see?

**Comment by headius** [comment]
I fixed all places in Pointer.java where I found similar references to `dst` that should be `src`.
