### ISSUE TITLE
Decode Pointer as Closure

### ISSUE THREAD

**Issue by SerCeMan** [jnr/jnr-ffi#43]
Hello.

Now i I write jnr-fuse library, it is a JNR wrapper for FUSE. One of my problems is to convert Pointer to Closure and i have to use hack for getting NativeConveterer<SomeClosure, Pointer> (https://github.com/SerCeMan/jnr-fuse/blob/master/src/main/java/jnr/ffi/provider/jffi/ClosureHelper.java). The biggest challenge is to get TypeMapper. Are there any plans for creating convinient public API for this?

**Comment by headius** [comment]
We'd love to work with you on any API changes needed to support this. However, I realize this is an old issue and any feature changes should probably be done as a new PR or separate issues. I'll close this for now, but know that we're still interested in such improvements :-)
