### ISSUE TITLE
ToNativeContext/FromNativeContext are null when invoking a ToNativeConverter/FromNativeConverter for a closure

### ISSUE THREAD

**Issue by mpoindexter** [jnr/jnr-ffi#49]
In ClosureUtil.getResultType and ClosureUtil.getParameterType the context is explicitly set to null.  This causes the emitted code to invoke the converters with a null to/from native context.  I tried setting the context in these methods, and it seems to work, is there a reason the native context is nulled in these methods?

I changed ClosureUtil line 59 from 

     return new jnr.ffi.provider.FromNativeType(declaredJavaClass, nativeType, annotations, converter, null);

to 

     return new jnr.ffi.provider.FromNativeType(declaredJavaClass, nativeType, annotations, converter, context);

**Comment by mpoindexter** [comment]
Here's what I changed in my local copy:

https://github.com/mpoindexter/jnr-ffi/commit/8e1e2c8f628748e139bcbc64e966433fa71afb10

**Comment by headius** [comment]
@mpoindexter If you're still out there, we'd love a PR including some test cases for this!
