### ISSUE TITLE
Bad LD_LIBRARY_PATH bits can get into load logic

### ISSUE THREAD

**Issue by headius** [jnr/jnr-ffi#53]
While trying to reproduce jruby/jruby#3409, I ended up setting LD_LIBRARY_PATH to `/lib32`, causing it to appear in java.library.path. For whatever reason, the filtering applied by #52 did not filter this path out, and I was able to cause the same error in a somewhat artificial way.

I think it worthwhile to figure out why the same filtering did not apply to my env var in case other users have a situation where they've got a bad (or unusual?) set of LD*_LIBRARY_PATHs that might trigger a similar bad library load.

**Comment by mkristian** [comment]
can not reproduce with current master of jnr-ffi (2.0.7-SNAPSHOT)
```
$ LD_LIBRARY_PATH=/lib32 bin/jruby -Xnative.verbose=true -e 'puts "--------";p ENV_JAVA["java.library.path"];puts "--------";require "ffi"'
Successfully loaded native POSIX impl.
--------
"/lib32:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"
--------
```

so I can not help here.

**Comment by headius** [comment]
I think our many iterations of tweaks for library searching have probably addressed my original issues.
