### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by krisskross** [jnr/jnr-ffi#64]
Are there any performance benchmarks available? I was curious to understand how much overhead can be expected and how it compares to JNI (and other libraries).

**Comment by headius** [comment]
We have done some testing for presentations, but not a formal suite of benchmarks to compare with raw JNI or other libraries like JNA. In our testing, however, the overall cost of making a simple native call is about what it is for hand-written JNI...significantly faster than JNA. As you start to use more advanced features, they add overhead too...but in most cases we (really, @wmeissner, the founder of the JNR projects) try to keep that overhead about what you'd have to accept to do the same features with JNI.

**Comment by krisskross** [comment]
Sounds excellent, thanks Charles!
