### ISSUE TITLE
Benchmarks compared to direct-mapped JNA?

### ISSUE THREAD

**Issue by Jire** [jnr/jnr-ffi#69]
I looked around and couldn't find any performance benchmarks in comparison to direct-mapped JNA.

I did my own tests against direct-mapped JNA for `WriteProcessMemory` and found most of the time JNR is the same speed or 10% faster at best, and sometimes it's actually slower.

**Comment by headius** [comment]
I did some benchmarks for a talk some years ago. They're in the slides here: http://www.oracle.com/technetwork/java/jvmls2013nutter-2013526.pdf

tldr: JNR has about 10x less overhead than JNA for a trivial call like `getpid`, including all JNI overhead they both share. JNR is about as close as you're going to get to straight JNI performance without bypassing JNI in some way.

A benchmark of memory access would most likely be heavily limited by the speed of memory operations over JNI and in hardware, so I suspect that's why you don't see as much gain.

I'd be happy to incorporate some benchmarks into the project, if you'd like to put together a PR!

**Comment by Jire** [comment]
@headius These benchmarks seem to be regular JNA vs. JNR, which I am well aware JNR wins by and large. What I'm interested in is direct-mapped JNA vs. JNR :smi

**Comment by headius** [comment]
I am not familiar with "direct-mapped JNA". Can you share your benchmarks?

**Comment by mnicky** [comment]
He's probably referring to https://github.com/java-native-access/jna/blob/master/www/DirectMapping.md

**Comment by headius** [comment]
@mnicky Thank you!

From that post, it seems like this wouldn't be a difficult thing to add to JNR, if it seemed valuable. Currently JNR has all sorts of plumbing for binding interfaces to native endpoints; mapping them to static methods would mostly be a matter of stripping out the interface/object logic and just generating the native binding directly.

Of course, if normal JNR is already as fast as JNA direct mapping, we may not be able to improve on that 😄

**Comment by konstantin-krasheninnikov-ullink** [comment]
I've done some JMH benchmarking for _gettimeofday_ for both JNA & JNR. Surprisingly direct mapping did not make any noticeable difference for JNA. JNR performance was much better and the numbers looked like what JNA direct mapping was advertising (order of 10 degradation in comparison with JNI or better). 

To compare it with Java Clock (apples to apples) I created a wrapper to construct an Instant from data returned by _gettimeofday_

```
Java 9-ea on Mac.
Benchmark                                      Mode  Cnt         Score        Error  Units
ClockBenchmark.benchClockUTCThroughput        thrpt  200  15945407.224 ± 112190.348  ops/s
ClockBenchmark.benchJnaClockUTCThroughput     thrpt  200    183084.868 ±  11434.751  ops/s
ClockBenchmark.benchJnrClockUTCThroughput     thrpt  200   3190489.816 ±  67041.235  ops/s

Java 8-66:
Benchmark 'benchClockUTCThroughput'       has score: 17721893.183 ops/s over 5 iterations.
Benchmark 'benchJnaClockUTCThroughput'    has score:   204396.310 ops/s over 5 iterations.
Benchmark 'benchJnrClockUTCThroughput'    has score:  3654995.188 ops/s over 5 iterations.
```

**Comment by neilcsmith-net** [comment]
What is it with benchmarks without source code?! 😞

**Comment by hc-codersatlas** [comment]
@konstantin-krasheninnikov-ullink can you explain the benchmark? So was JNA direct mapping compared to JNR?

**Comment by neilcsmith-net** [comment]
Yes, @konstantin-krasheninnikov-ullink - share the benchmark code or it didn't happen! :wink:

**Comment by headius** [comment]
If someone would like to contribute some benchmarks, please open a PR.
