### ISSUE TITLE
Doc + thread safety 

### ISSUE THREAD

**Issue by aconstnull** [jnr/jnr-ffi#70]
Using JNR and love it! Three questions:
1) where's the right place to ask questions ;) 
2) Thread safety: is it safe to make concurrent calls via a generated lib interface sharing the same Runtime? (Seems to work but wanted to check)
3) Any docs on how jnr works anywhere? Watched the presentation on YouTube - but a bit high level 

Any info much appreciated!

**Comment by goto1134** [comment]
1) stackoverflow is great for this.
3) javadoc is ok for jnr, but not everything is clear, you need to google or test or look in other projects to find out some usecases.

**Comment by aconstnull** [comment]
Thanks! 
I now finally found this one by Charles: 
https://m.youtube.com/watch?v=94tQ4bEwa6o

Libffi clears it up for me :) 

Looks like the thread safety question also answered by the fact that errno is held ThreadLocal (and thus why you can get a perf boost with @IgnoreError )

Looking forward to making more and more use of this fantastic library!

**Comment by headius** [comment]
2) jnr-* are expected to themselves be thread-safe, but obviously they make no guarantees about the library you're calling. If a thread-safety issue were reported, we'd fix it.

I think all your items have been addressed, so I'll close this. Thanks for your interest!
