### ISSUE TITLE
Struct$Pointer fields work only with Direct jnr.ffi.Pointer.

### ISSUE THREAD

**Issue by goto1134** [jnr/jnr-ffi#81]
If you will try to put not Direct  jnr.ffi.Pointer in this field, you will not be able to get the same value. I think, this is a confusing a lot. To solve this, I think we need a method like directCopy for  jnr.ffi.Pointer.

**Comment by headius** [comment]
Can you give me an example?

**Comment by headius** [comment]
Let me elaborate a bit on that :-)

If this is indeed a problem, we should fix it. Your suggestion seems fine but I'd like to see a failing test or example first.

**Comment by headius** [comment]
Ping @goto1134 one more time about this :-) I'd like to do a bunch of JNR releases today.

**Comment by goto1134** [comment]
ok, I've got an idea, but don't think it's very good. We can just copy all bytes to direct(or temp) memory and write it's address in the pointer memory. But what about the memory leaks? @headius

**Comment by headius** [comment]
@goto1134 I wouldn't consider this a leak, since we have other ref types that also copy rather than reference the original native memory.

**Comment by headius** [comment]
I am not sure if #85 provided what you needed, but this issue has gone a bit stale. If there's more work to do related to this, open a new issue with some example code you expect to work.
