### ISSUE TITLE
Make Struct.Function public

### ISSUE THREAD

**Issue by ahilananantha** [jnr/jnr-ffi#87]
Right now Struct.Function is protected which prevents us from assigning the value of the function pointer after construction of the derived Struct class. Most of the other inner classes are declared public which allows assignment and update at any time so it seems like an oversight to not make this one public too.

The reason this is useful is when you are wrapping a C-api where you need to implement callbacks. For different implementations you will want to specify different callbacks. So your derived Struct will only be initializing the function pointers to zero and an owning class would set them. As a workaround I'm following the same strategy as the developer of jnr-fuse... define my own AbstractMember that is a straight copy of Function but made public. But I really don't want to duplicate code.

**Comment by headius** [comment]
Toss us a PR! 😄
